language: node_js
node_js:
  - "10"
notifications:
  email: false
services:
  - postgresql
cache:
  directories:
    - "node_modules"
env:
    global: CC_TEST_REPORTER_ID=0ea72ec902bfd13d332a067ffed6fea23f2e6b7a21f6a62daa7877a7ba4373a6
before_script:
  - psql -c "CREATE DATABASE quickcredit_test;" -U postgres
  - psql -c "CREATE USER odunayo WITH PASSWORD 'password';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - "npm run nyc"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT